name: Build and Deploy

# only run on changes to master
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-cloudflare
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.140.2
    steps:
    - name: Install Hugo CLI
      run: |
           wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-amd64.deb \
           && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - uses: actions/checkout@v1
      with:
        submodules: true 
    - name: Build with Hugo
      run: hugo
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy public/ --branch=main --project-name=melvis-dnd --commit-dirty=true
      
